name: Regenerate Resource Files

on:
  push:
    paths:
      - ".github/workflows/images.yml"
      - "img/**"
      - "tools/generate-assets.sh"
  workflow_dispatch:

jobs:
  regenerate-assets:
    name: Regenerate Image Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate Assets
        run: tools/generate-assets.sh